<?php

/*
Plugin Name: Plugin #616366
Description: Add code to the bottom of non-admin pages. This plugin will display a message in the center of all non-admin pages, and display a console message on page load via jQuery.
Version: 1.0
Author: Aaron Ritchey
Author URI: http://aaronritchey.com

The original plugin name, "Add to Footer", confused WordPress enough for it to suggest I
  update this plugin to v1.3 of https://wordpress.org/plugins/add-to-footer/
*/

// Prevent direct access to this file.
defined( 'ABSPATH' ) or die( );


if (!is_admin()) {
    add_action('wp_footer', 'x616366_wp_footer');
}

function x616366_wp_footer() {

    // Including opening/closing comments helps others know which plugin
    //   generated this code.
    print "\n<!-- code generated by plugin #616366 -->\n";

	x616366_add_floating_box();
	x616366_add_javascript();
	
    print "<!-- END code generated by plugin #616366 -->\n\n";

}

// Nothing exciting, just adding a quick floating box.
function x616366_add_floating_box() {
?>
<style>
	/* This plugin is for learning about WordPress, so */
	/*   no comments will be written for the CSS below. */
	#content {
		position: relative;
	}
	.plugin_616336_message {
		position: fixed;
		top: 50%;
		left: 50%;
		background-color: #ffddaa;
		border: 3px ridge #ffddaa;
		padding: 0.5em;
	}
</style>
<div class="plugin_616336_message">Hello from Plugin #616366</div>
<?php
} // END x616366_add_floating_box



// Nothing exciting, just adding some JavaScript.
function x616366_add_javascript() {
?>
<script>
	// A simple alert, inserted by this plugin.
	jQuery(document).ready( function($) {
		console.log('This jQuery executes when the page is ready.');
		console.log('Analytics code can also be added here.');
	});
</script>
<?php
} // END x616366_add_javascript
